client_id = "55db873a11642b8a25325fec3257209a"
name = "FlashDrop"
application_url = "https://cart-timer.apps-alchemy.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_discounts"

[auth]
redirect_urls = [ "https://cart-timer.apps-alchemy.com/auth/callback" ]

[app_proxy]
url = "https://cart-timer.apps-alchemy.com/api/storefront"
subpath = "timer"
prefix = "apps"